version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/map_my_world
      - DATABASE_TEST_URL=sqlite:///./map_my_world.db
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=map_my_world
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "shared_preload_libraries=pg_trgm"]


volumes:
  postgres_data: